#pragma once

#define LED_USER C13

#ifdef AUDIO_ENABLE
# define AUDIO_PIN A4
# define AUDIO_STATE_TIMER GPTD3
# define CAPS_SOUND SIXTEENTH_NOTE(_A3), SIXTEENTH_NOTE(_B3),
# define DIRS_X1_SOUND THIRTYSECOND_DOT_NOTE(_C2)
# define DIRS_X2_SOUND THIRTYSECOND_DOT_NOTE(_C3)
# define DIRS_X4_SOUND THIRTYSECOND_DOT_NOTE(_C4)
#endif

#define KEYNCODER_THRESHOLD_X2 100
#define KEYNCODER_THRESHOLD_X4 50
